### ISSUE TITLE
!important(s) in framework are preventing overrides

### ISSUE THREAD

**Issue by FelFly** [Esri/calcite-bootstrap#255] opened 2016-04-25 14:39 UTC
Trying to upgrade from 0.2.12 to 0.3.2 caused some style changes to Open Data, which don't look so good. I'd like to be able to customize the design to keep what we had in the 0.2.12 version, but the use of `!important` at the framework level is blocking me from editing our CSS to do so. Most critcally lines 9-10 in [_nav-tabs-custom.scss](https://github.com/Esri/calcite-bootstrap/blob/master/lib/sass/calcite/_navs-tabs-custom.scss#L9) (since we have tabs that exist mid-page, we really need a border on all sides) and to a lesser degree [_dropdowns-custom](https://github.com/Esri/calcite-bootstrap/blob/master/lib/sass/calcite/_dropdowns-custom.scss#L40).

**Comment by julio8a** [comment] 2016-04-25 16:25
This is the same issue we're having on Dashboard

**Comment by julio8a** [comment] 2016-04-29 22:10
I think there's a larger issue here, which @ffaubry  and I discovered on the Operations Dashboard...

The way we were loading Calcite Bootstrap on dashboard was:

app.scss:
```
@import 'app/config'
@import 'calcite-bootstrap'
@import 'app/main'
```

app/main.scss (from above):
```
@import 'fonts'
@import 'bootstrap'
@import 'variables'
+ other import styles that are unique to Dashboard
```

The issue is that calcite bootstrap is loaded first, then we load main.scss which contains bootstrap and variables. Therefore, bootstrap overrides the components inside calcite bootstrap.

Which could be the reason why there are ```!important``` tags on calcite-bootstrap components... to supersede bootstrap. Therefore, anytime we want to change something from calcite-bootstrap we'd have to use ```!important``` to supersede the ```!important``` on calcite-bootstrap components. 

The ideal load order we need is:
```
@import 'variables'
@import 'bootstrap'
@import 'calcite-bootstrap'
```
^^^ This should solve the need to use ```!important``` on calcite-bootstrap components.

bootstrap has to be loaded after variables, but before calcite-bootstrap (so that components.scss inside calcite bootstrap is not overwritten by bootstrap, which is currently loaded after).

Workforce's workaround is sourcing the scss files individually, which is something we are now mimicking on Dashboard.
Workforce app.scss:
```
@import calcite/colors-default
@import calcite/calcite

$icon-font-path: '/fonts/bootstrap/'

@import bootstrap
@import calcite-bootstrap
+ Workforce unique scss files
```

Dashboard's app.scss:
```
@import 'calcite/colors-default';   // Load calcite color variables
@import 'app/fonts';                // Load the ops dashboard fonts
@import 'calcite/variables';        // Load the calcite bootstrap override
$icon-font-path: './fonts/';        // Re-define the path where the icon fonts are stored for bootstrap
@import 'bootstrap';                // Load bootstrap
@import 'calcite/components';       // Load calcite element and class styles and overrides
@import 'app/main';                 // Load ops dashboard specific element and class styles and overrides
```

This is the work around for loading calcite-bootstrap after bootstrap, which gives us all of the Esri styles we applied to calcite-bootstrap. Again, not ideal... I think we need to reassess the structure. 
 
@ffaubry feel free to add anything I missed.

**Comment by FelFly** [comment] 2016-05-02 11:44
Well the way that Open Data loads this in is:

```
@import theme // custom theme / shared styling
@import themes/bootstrap-expansion // sets default theme for bootstrap vars for Open Data customers
@import themes/calcite-bootstrap-expansion // sets default theme on some calcite variables
@import bootstrap/_variables
@import components/calcite-bootstrap
@import bootstrap/[components] //not including full list
@import components/[open-data-specific]
```
Pretty much everything in boostrap-expansion and calcite-bootstrap-expansion is set to `!default`, so that a custom theme can be brought in and either custom variables or bootstrap variables are set there, but then used again in Open Data specific components. 



```

**Comment by mjuniper** [comment] 2016-05-02 12:45
@julio8a I agree and I have always thought the load order seemed wrong and possibly indicative of a larger issue. What can we do about this?

**Comment by julio8a** [comment] 2016-06-06 16:32
All important tags removed here: #271 

closing this out

**Closed by julio8a** 2016-06-06 16:32 UTC
Labels: bug
